### ISSUE TITLE
数据处理和衡量问题

### ISSUE THREAD

**Issue by JUSTWILLPOWER** [caoxu907/MMWAVE_gait#1]
你好，我看了你的论文，感觉非常感兴趣，我有个疑问就是，在跟踪准确性上，是否具有正确移动位置的坐标呢？我看数据集里面好像没有提供

**Comment by caoxu907** [comment]
你好，我们没有做位置跟踪，做的是步态识别，所以不需要准确位置信息

**Comment by JUSTWILLPOWER** [comment]
> 你好，我们没有做位置跟踪，做的是步态识别，所以不需要准确位置信息

哦哦，好的。
